language: rust
rust:
  - stable
#  - 1.31.0
#  - 1.22.0
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check --verbose
  - cd libtor-derive
  - cargo fmt -- --check --verbose
  - cd ..
  - cargo test -vv

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
cache: cargo

notifications:
  email: false
